#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: 2.1

executors:
  daml-executor:
    docker:
      - image: cimg/openjdk:11.0

commands:
  install_sdk:
    description: "Install Daml SDK"
    parameters:
      version:
        type: string
    steps:
      - run:
          name: Install Daml SDK
          command: |
            curl -sSL https://get.daml.com/ | sh /dev/stdin << parameters.version >>
            # idea from https://circleci.com/docs/2.0/env-vars/
            >> $BASH_ENV echo 'export PATH="$HOME/.daml/bin:$PATH"'
  install_yq:
    description: "Install yq from binary"
    steps:
      - run:
          name: Install yq
          command: |
            mkdir -p $HOME/yq
            curl -L https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -o $HOME/yq/yq &&\
              chmod +x $HOME/yq/yq &&\
              echo 'export PATH=$HOME/yq/yq:$PATH' >> $BASH_ENV
  install_gh:
    description: "Install GitHub Cli"
    steps:
      - run:
          name: Install gh
          command: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
  set_sdk_version:
    description: "Set Daml SDK version environment version"
    steps:
      - run:
          name: Set Daml SDK version
          command: echo 'export SDK_VERSION=$(yq e '.sdk-version' daml.yaml)' >> $BASH_ENV
  get_dependencies:
    description: "Get project data-dependencies from Github"
    steps:
      - run:
          name: Get data-dependencies
          command: |
            readarray DEPENDENCIES < <(yq e '.data-dependencies[]' daml.yaml)
            for DEPENDENCYPATH in "${DEPENDENCIES[@]}"; do

              # Take the full path, split on the unix file separator and take the last element in array
              FILENAME=`awk '{ n=split($0,array,"/"); print array[n] }' \<<< ${DEPENDENCYPATH}`

              # From the end of the file name, remove the file extension and the version to get the repo name
              REPO=`awk '{ sub(/\-[0-9]*\..*$/, "") ; print }' \<<< ${FILENAME}`

              # Match from the major version until the end of the file name; keep what was matched from the input string; remove the file extension
              VERSION=`awk '{ match($0, /[0-9a-zA-Z]+\..*/) ; $0=substr($0, RSTART, RLENGTH); sub(/.[a-z]+$/, ""); print }' \<<< ${FILENAME}`

              echo "Downloading ${FILENAME} from Github repository at https://github.com/digital-asset/${REPO}/releases/download/v${VERSION}/${FILENAME}"
              curl -Lf# https://github.com/digital-asset/${REPO}/releases/download/v${VERSION}/${FILENAME} -o ${DEPENDENCYPATH}
              echo ""
              echo "${FILENAME} downloaded successfully! Dependency saved to ${DEPENDENCYPATH}"
              echo ""
            done
  run_release:
    description: "Run Release"
    steps:
      - run:
          name: "Get target release version"
          command: echo 'export VERSION=$(yq e '.version' daml.yaml)' >> $BASH_ENV
      - run:
          name: "Validate target release version"
          command: |
            if [ `git tag` == $VERSION ] ; then
              echo "New tag detected ${VERSION}. Releasing..."
            else
              echo "Tag ${VERSION} already exists; Skipping Release."
              circleci-agent step halt
            fi
      - run:
          name: "Tag and push to GitHub"
          command: gh release create v${VERSION} .daml/dist/contingent-claims-${VERSION}.dar --generate-notes
      - store_artifacts:
          path: .daml/dist/contingent-claims-${VERSION}.dar
          destination: contingent-claims-dar-${VERSION}

jobs:
  build:
    executor: daml-executor
    steps:
      - checkout
      - install_yq
      - set_sdk_version
      - restore_cache:
          keys:
            - contingent-claims-{{ checksum "daml.yaml" }}
      - install_sdk:
          version: ${VERSION}
      - get_dependencies
      - run:
          name: Build Daml
          command: |
            daml build
      - run:
          name: Daml tests
          command: |
            cd test
            daml test
      - save_cache:
          paths:
            - .daml
          key: contingent-claims-{{ checksum "daml.yaml" }}

  release:
    executor: daml-executor
    steps:
      - checkout
      - install_yq
      - install_gh
      - restore_cache:
          keys:
            - contingent-claims-{{ checksum "daml.yaml" }}
      - run_release

  blackduck:
    executor: daml-executor
    steps:
      - checkout
      - run:
          name: Blackduck detect
          command: |
            bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
            ci-build digitalasset_contingent-claims master \
            --logging.level.com.synopsys.integration=DEBUG \
            --detect.excluded.detector.types=pip \
            --detect.notices.report=false \
            --detect.timeout=3600

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
  build_and_release:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - release:
          context: github-fin-eng-context
          requires:
            - build
          filters:
            branches:
              only:
                - master
  scheduled_test:
    triggers:
      - schedule:
          # need to scatter jobs to reduce Blackduck load
          # see also https://digitalasset.atlassian.net/browse/ERA-913
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - blackduck:
          context:
            - blackduck
