git add docs
git stash push -m "Autogenerated documentation for publishing on github pages" -- docs
git switch github-pages
rm docs/*.html
git stash pop
for f in docs/*.html 
  do pandoc -s --template da-style/da-pandoc.html --metadata pagetitle="Contingent Claims" -o $f $f 
done
