git add docs
git stash push -m "Autogenerated documentation for publishing on github pages" -- docs
git switch github-pages || exit
git merge -s recursive -X theirs refs/stash
for f in docs/*.html 
  do pandoc -s --template docs/da-style/da-pandoc.html --metadata pagetitle="Contingent Claims" -o $f $f 
done
git add docs

git stash drop
